[package]
name = "russh"
version = "0.1.0"
authors = ["jan <jan@stdpixel.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
yaml-rust = "0.4.3"
colored = "1.8"
prettytable-rs = "0.8.0"
slot = { path = "lib/slot" }
